### ISSUE TITLE
Import error on fresh install or 2.0.11

### ISSUE THREAD

**Issue by chatch** [chatch/pinyin-toolkit#11]
Seeing the following error on a fresh install of 2.0.11:

An error occurred in an add-on.
Please post on the add-on forum:
https://groups.google.com/forum/#!forum/anki-addons

Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 39, in loadAddons
    **import**(file.replace(".py", ""))
  File "/home/ubuntu/Anki/addons/Pinyin Toolkit.py", line 29, in <module>
    import pinyin.anki.main as main
  File "/home/ubuntu/Anki/addons/pinyin/**init**.py", line 13, in <module>
    import config
  File "/home/ubuntu/Anki/addons/pinyin/config.py", line 8, in <module>
    import dictionaryonline
  File "/home/ubuntu/Anki/addons/pinyin/dictionaryonline.py", line 8, in <module>
    from model import Text, Word
  File "/home/ubuntu/Anki/addons/pinyin/model.py", line 11, in <module>
    from db import database
  File "/home/ubuntu/Anki/addons/pinyin/db/**init**.py", line 1, in <module>
    import cjklib.dbconnector
ImportError: No module named cjklib.dbconnector

**Comment by chatch** [comment]
This is due to missing cjklib directory beacuse I did not fetch git submodules on build.

Going to rebuild the plugin correctly then close this issue ..

**Comment by chatch** [comment]
Rebundled with the cjklib and uploaded to anki web -> https://ankiweb.net/shared/info/2554990764
