### ISSUE TITLE
On "Reformat readings" of my deck: ValueError: too many values to unpack

### ISSUE THREAD

**Issue by chambm** [chatch/pinyin-toolkit#14]
Traceback (most recent call last):
  File "D:\Users\Matt\Documents\Anki\addons\pinyin\anki\hooks.py", line 208, in <lambda>
    function = lambda: runBulkFill(mw, config, notifier, updaters, field, updatehow, notification)
  File "D:\Users\Matt\Documents\Anki\addons\pinyin\anki\hooks.py", line 257, in runBulkFill
    getattr(updaters[field], updatehow)(factproxy, factproxy[field])
  File "D:\Users\Matt\Documents\Anki\addons\pinyin\updater.py", line 119, in updatefactalways
    fact['reading'] = preparetokens(self.config, [model.Word(*model.tokenize(reading))])
  File "D:\Users\Matt\Documents\Anki\addons\pinyin\model.py", line 435, in tokenize
    recurse([], BeautifulSoup(html))
  File "D:\Users\Matt\Documents\Anki\addons\pinyin\model.py", line 421, in recurse
    thisattributesstack = attributesstack + [extract_attr_maybe(attrsdict, "style", "color", take_style_val("color"))]
  File "D:\Users\Matt\Documents\Anki\addons\pinyin\model.py", line 340, in extract_attr_maybe
    res = extractor(attrs[attr])
  File "D:\Users\Matt\Documents\Anki\addons\pinyin\model.py", line 391, in go
    return (value, unparse_style((intelligible, unintelligible)))
  File "D:\Users\Matt\Documents\Anki\addons\pinyin\model.py", line 378, in unparse_style
    return "; ".join([k + " : " + v for k, v in intelligible] + unintelligible)
ValueError: too many values to unpack

If this is a problem with a particular one of my cards, how can I determine which one?

**Comment by chatch** [comment]
There is no way to tell as it stands ... I'll take a look at this and see if I can't replicate it anyway .. If not I'll create a version that has some logging and send it to you to run and that will hopefully shed some light on the problem.
