### ISSUE TITLE
Preferences broken on Mac

### ISSUE THREAD

**Issue by chatch** [chatch/pinyin-toolkit#7]
Reported on the addon forum:

It works on Mac for filling in fields with colours and tones, but throws an error when I try to open the preferences dialog.

An error occurred in an add-on. Please contact the add-on author.

Traceback (most recent call last):

File "/Users/joel/Documents/Anki/addons/pinyin/anki/hooks.py", line 190, in

function = lambda: openPreferences(mw, config, notifier, mediamanager)

File "/Users/joel/Documents/Anki/addons/pinyin/anki/hooks.py", line 232, in openPreferences

controller = pinyin.forms.preferencescontroller.PreferencesController(preferences, notifier, mediamanager, config)

File "/Users/joel/Documents/Anki/addons/pinyin/forms/preferencescontroller.py", line 53, in **init**

self.updateViewPreview()

File "/Users/joel/Documents/Anki/addons/pinyin/forms/preferencescontroller.py", line 231, in updateViewPreview

self.updaterfromexpr.updatefact(fact, previewexpressions[self.model.prefersimptrad])

File "/Users/joel/Documents/Anki/addons/pinyin/updater.py", line 320, in updatefact

meaning = self.generatemeanings(expression, dictmeanings)

File "/Users/joel/Documents/Anki/addons/pinyin/updater.py", line 148, in generatemeanings

dictmeanings = [transformations.tonesandhi(dictmeaning) for dictmeaning in dictmeanings]

File "/Users/joel/Documents/Anki/addons/pinyin/transformations.py", line 72, in tonesandhi

finalwords.append(word.map(applyvisitor))

File "/Users/joel/Documents/Anki/addons/pinyin/model.py", line 480, in map

word.append(token.accept(visitor))

File "/Users/joel/Documents/Anki/addons/pinyin/model.py", line 259, in accept

return visitor.visitTonedCharacter(self)

File "/Users/joel/Documents/Anki/addons/pinyin/transformations.py", line 103, in visitTonedCharacter

return TonedCharacter(unicode(tonedcharacter), ToneInfo(written=tonedcharacter.toneinfo.written, spoken=int(self.tonecontourqueue.pop())))

ValueError: invalid literal for int() with base 10: '_'

**Comment by chatch** [comment]
Fixed by idavydov
